[package]
name = "web-midi-player-core"
version = "0.2.1"
edition = "2024"
license = "MIT"
description = "Core MIDI parsing + SF2 synthesis (Wasm) for web-midi-player"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
log = "0.4"
ump-playback = { git = "https://github.com/yuiAs/ump", rev = "0e4ddce51ee3bf2d03ad076c531ae0d7a22cb6ee" }
web-sys = { version = "0.3", features = ["console"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
